version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
    container_name: app
    expose:
      - "80"
    ports:
      - "80:80"
